# Generated by Django 5.2.15 on 2026-06-22 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('cartao_utilizado', models.CharField(choices=[('Nubank', 'Nubank'), ('Banco Inter', 'Banco Inter'), ('C6 Bank', 'C6 Bank'), ('Itaú', 'Itaú'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander'), ('Caixa', 'Caixa'), ('Banco do Brasil', 'Banco do Brasil'), ('Outro', 'Outro (Especificar no nome)')], default='Nubank', max_length=100, verbose_name='Cartão Utilizado')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total (R$)')),
                ('valor_parcela', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor de Cada Parcela (R$)')),
                ('valor_faltante', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Faltante (R$)')),
                ('parcelas_totais', models.IntegerField(verbose_name='Quantidade de Parcelas Totais')),
                ('parcelas_pagas', models.IntegerField(default=0, verbose_name='Quantidade de Parcelas Pagas')),
                ('parcelas_faltantes', models.IntegerField(default=0, verbose_name='Quantidade de Parcelas Faltantes')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Empréstimo')),
                ('usuario_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono do Registro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
